# Usar uma imagem base oficial do Python
FROM python:3.9

# Definir o diretório de trabalho no container
WORKDIR /app

# Copiar os requisitos do projeto para o diretório de trabalho
COPY requirements.txt .

# Instalar as dependências
RUN pip install --no-cache-dir -r requirements.txt

# Copiar o restante do código do projeto para o diretório de trabalho
COPY . .

# Expor a porta que a aplicação vai rodar
EXPOSE 7070

# Comando para rodar a aplicação
CMD ["python", "app.py"]
